apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.fullname" . }}-secrets
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
type: Opaque
data:
  # These will be populated from GitHub secrets during deployment
  NEXTAUTH_SECRET: {{ .Values.secrets.NEXTAUTH_SECRET | b64enc | quote }}
  CLIENT_SECRET_GITHUB: {{ .Values.secrets.CLIENT_SECRET_GITHUB | b64enc | quote }}
  BACKEND_SECRET: {{ .Values.secrets.BACKEND_SECRET | b64enc | quote }}
  FORTY_TWO_CLIENT_SECRET: {{ .Values.secrets.FORTY_TWO_CLIENT_SECRET | b64enc | quote }} 
  NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: {{ .Values.secrets.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY | quote }}